spring.datasource:
  driverCLassName: org.h2.Driver
  url: jdbc:h2:file:C:/dummy
  username: admin
  password: 

spring.jpa.hibernate:
  dialect: org.hibernate.dialect.MySQLInnoDBDialect
  ddl-auto: update

---

spring.profiles: integration-test

spring.datasource:
  driverCLassName: com.mysql.jdbc.Driver
  url: jdbc:h2:mem:haushalt_mem
  username: 
  password: 
